// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ajalck/CRUD_With_PSQL/pkg/handlers"
	"github.com/ajalck/CRUD_With_PSQL/pkg/repository"
	"github.com/ajalck/CRUD_With_PSQL/pkg/router"
	"github.com/ajalck/CRUD_With_PSQL/pkg/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApi(db *gorm.DB) (*router.ServeHTTP, error) {
	repo := repository.NewDB(db)
	useCase := usecase.NewUseCase(repo)
	handlersHandlers := handlers.NewHandler(useCase)
	serveHTTP := router.NewServeHTTP(handlersHandlers)
	return serveHTTP, nil
}
